#!/bin/bash

set -x

NAME_REGISTRY="gcr.io/spectro-common-dev/tylergillson"

LIST_IMAGES="\
	ubuntu;22.10;https://cloud-images.ubuntu.com/kinetic/current/kinetic-server-cloudimg-amd64.img \
	ubuntu;22.04;https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img \
	ubuntu;20.04;https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img \
	fedora;36;https://ftp.cica.es/fedora/linux/releases/36/Cloud/x86_64/images/Fedora-Cloud-Base-36-1.5.x86_64.qcow2 \
	fedora;37;https://ftp.cica.es/fedora/linux/releases/37/Cloud/x86_64/images/Fedora-Cloud-Base-37-1.7.x86_64.qcow2 \
"
echo "$LIST_IMAGES"

for IMAGE in $LIST_IMAGES
do
	OS_NAME=$(echo $IMAGE | cut -d";" -f1)
	OS_VERSION=$(echo $IMAGE | cut -d";" -f2)
	IMAGE_URL=$(echo $IMAGE | cut -d";" -f3)
	URL_LIST=($(echo "$IMAGE_URL" | tr "/" " "))
	FILE_NAME="${URL_LIST[${#URL_LIST[@]}-1]}"
	NAME_IMAGE="$OS_NAME-container-disk"
	FILE_LIST=($(echo "$FILE_NAME" | tr "." " "))
	IMAGE_NAME=$(echo $FILE_NAME | cut -d"." -f1)
	IMAGE_EXTENSION="${FILE_LIST[${#FILE_LIST[@]}-1]}"

	echo "OS:$OS_NAME VERSION:$OS_VERSION IMAGE:$IMAGE_URL"
	echo "Build $NAME_REGISTRY/$NAME_IMAGE:$OS_VERSION"

	docker build -f base/Dockerfile -t $NAME_REGISTRY/$NAME_IMAGE:$OS_VERSION \
		--build-arg OS_NAME="$OS_NAME" \
		--build-arg OS_VERSION="$OS_VERSION" \
		--build-arg IMAGE_URL="$IMAGE_URL" \
		--build-arg FILE_NAME="$FILE_NAME" \
		--build-arg IMAGE_NAME="$IMAGE_NAME" \
		--build-arg IMAGE_EXTENSION="$IMAGE_EXTENSION" .

	docker push $NAME_REGISTRY/$NAME_IMAGE:$OS_VERSION
done